### ISSUE TITLE
boards.fireden.net support

### ISSUE THREAD

**Issue by panhartstuff** [pboardman/4scanner#66]
Can you please add support for https://boards.fireden.net
Your help will really be appreciated!

**Comment by pboardman** [comment]
Hello! I'd like to add it but it seems like FoolFuuka (The imageboard software running the site) does not support the json API that imageboards usually implement. (ex: [4chan's /g/ board catalog page as json](http://a.4cdn.org/g/catalog.json)) This API is needed by 4scanner to be able to work so I can't easily support it :(

I may try to support imageboards running "non-standard" software in the future but it's not really planned right now unfortunately.

**Comment by pboardman** [comment]
I will close the issue for now. If an API is implemented for it sometime in the future we can reopen it but in the meantime I cannot support it 😢
