### ISSUE TITLE
Scan only the "Subject" field

### ISSUE THREAD

**Issue by panhartstuff** [pboardman/4scanner#67]
A useful feature to add is to be able to scan for keywords only within the "Subject" field. This could greatly narrow down our search results

**Comment by panhartstuff** [comment]
Thank you for the fast response!!

**Comment by pboardman** [comment]
Added in #68 (4scanner 1.6.1) which I just uploaded to pypi! So you should be able to update with `pip` and use the new `subject_only` parameter (see [OPTIONS.md](https://github.com/pboardman/4scanner/blob/master/OPTIONS.md) for info)

If you have any problem with it feel free to reopen the issue.
