### ISSUE TITLE
Clarification on the instructions

### ISSUE THREAD

**Issue by PisauraXTX** [pboardman/4scanner#69]
Hi, I'm having some trouble following the instructions which I was hoping you could clear up for me. 
First, in the section "Installing". 

> ` pip3 install 4scanner `

Am I supposed to copy and paste this somewhere and run it? If so, where? 
Second, where does '4genconf' put the file it is supposed to create? I was unable to find it anywhere within the folder structure. Editing the 'example.json' file was not a problem though. 
Third, in the section "How to" 

> ` 4scanner file.json `

I take it 'file' is a stand-in for whatever json config file I want to run the script on. Again, where and how am I supposed to run this command? I tried this with several consoles and programming notebooks in several folders and none of them worked. 
Thank you for your help.

**Comment by pboardman** [comment]
Hello!

`pip3` (or just `pip` if you have only python3 installed on your system) is a terminal command that is automatically installed when you install python. If you don't have python installed you need to get it (version 3.4+) before running this command.

After running `pip3 install 4scanner` inside a terminal you should get access to `4scanner`, `4downloader` and `4genconf` from any terminal window. (You don't need to download the repository at all, the `pip` install command will setup everything.

`4genconf` should create the configuration file in the directory you are currently in.
