### ISSUE TITLE
Save directory as thread name instead of ID

### ISSUE THREAD

**Issue by demib72** [pboardman/4scanner#80]
Using a webscraper such as Beautifulsoup, might it be possible to save directories as the thread name instead of the ID? When I have the free time, I am thinking of experimenting with this (can use an archive site for 404'd threads) and/or scraping the replies as a document with the photos.

**Comment by pboardman** [comment]
Hello! Yes I think that would make searching the pictures a lot easier! If you want to give it a go we can definitely merge it in 4scanner 😀

**Comment by demib72** [comment]
If there is a way to save the jsons from 4chan, the name can be pulled from "com" keyname at the beginning of the file. Haven't figured where in the code that downloads the json for 4scanner to use yet. Haven't had the time.

**Comment by demib72** [comment]
I have a basic working prototype that I have been running for the last week. Could you make a development branch? I am not too comfortable with making a pull request right into master.

**Comment by pboardman** [comment]
Hey! It's fine you can just create a pull request in the master branch and I will test it before merging 🙂
